# This file is generated by update_registry script. Do not edit!
enginesByType = {
    'raw'   : 'Raw',
    'pyem'  : 'PythonEmbedded',
    'pysi'  : 'PySI',
    'dtml'  : 'DTML',
    'xtal'  : 'XMLTAL',
    'htal'  : 'HTMLTAL',
    'xhtal' : 'XHTMLTAL',
}
